name = "StaticPermutations"
uuid = "15972242-4b8f-49a0-b8a1-9ac0e7a1a45d"
authors = ["Juan Ignacio Polanco <jipolanc@gmail.com> and contributors"]
version = "0.1.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.3"
